info:
  title: Docs Demo
  version: v0.0.1
openapi: 3.0.0
paths:
  /api/potato:
    post:
      description: ''
      responses:
        '200':
          description: no error
      summary: This endpoint is POST /api/potato.
  /api/user:
    get:
      description: ''
      responses:
        '200':
          description: no error
        '404':
          description: there's no user
      summary: This endpoint is GET /api/user.
  /api/user/<id>:
    post:
      description: 'Here we''ll have some more details about the API.


        This is some more text to check that the **description** _works_ well.



        Please note the following things:


        Here is more stuff at the end!'
      parameters:
      - description: the id of the user
        in: path
        name: id
        required: true
        schema:
          type: integer
      - description: one of `hit`, `created-at`
        in: query
        name: sort
        schema:
          type: integer
      - description: offset number. default is 0
        in: query
        name: offset
        schema:
          type: integer
      - description: limit number. default is 30
        in: query
        name: limit
        schema:
          type: integer
      - description: the response content type depends on the :mailheader:`Accept`
          header
        in: header
        name: Accept
        schema:
          type: string
      - description: optional OAuth token to authenticate
        in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                age:
                  type: integer
                name:
                  type: string
              type: object
          multipart/form-data:
            schema:
              properties:
                age:
                  type: integer
                name:
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  success:
                    description: whether the operation succeeded
                    type: boolean
                type: object
          description: no error
          headers:
            Content-Type:
              description: this depends on the :mailheader:`Accept` header of request
              schema:
                type: string
        '404':
          description: there's no user
      summary: This endpoint is POST /api/user/<id>.
